import { Pressable, Share, StyleSheet, Text, View } from 'react-native';
import React, { FC } from 'react';
import { DietStackScreenProps } from '../../types';
import { useColors } from '../../store';
import { goBack, rs, useSafeInsets } from '../../utils';
import { MEAL_META, MealType } from '../../helper';
import { useActiveDietPlan } from '../../hooks';
import {
  Badge,
  Button,
  Icon,
  ScreenWrapper,
  universalStyles,
} from '../../components';
import { fonts } from '../../constants';
import LinearGradient from 'react-native-linear-gradient';
import { MacroBar } from './components';

type Props = DietStackScreenProps<'MealDetail'>;

const MealDetailScreen: FC<Props> = ({ route }) => {
  const { mealType, dayIndex } = route.params;
  const colors = useColors();
  const insets = useSafeInsets();
  const meta = MEAL_META[mealType as MealType];

  const { data } = useActiveDietPlan();
  const plan = data?.plan;
  const meal = plan?.days?.[dayIndex]?.meals?.[mealType as MealType];

  const handleShare = async () => {
    if (!meal) return;
    try {
      await Share.share({
        message: `🍽️ ${meta?.label} from my FitSutra plan:\n\n${
          meal.name
        }\n📊 ${meal.calories} kcal | P: ${meal.protein}g | C: ${
          meal.carbs
        }g | F: ${meal.fat}g\n\n🛒 Ingredients: ${
          meal.ingredients?.join(', ') ?? 'N/A'
        }\n\n⏱️ Prep time: ${meal.prepTime} min\n\nGenerated by FitSutra AI 💪`,
        title: meal.name,
      });
    } catch {
      /* ignore share cancel */
    }
  };

  if (!meal) {
    return (
      <ScreenWrapper>
        <View style={[s.closeBtn, { top: insets.top + rs.verticalScale(16) }]}>
          <Pressable
            onPress={goBack}
            style={[
              s.closeBtnInner,
              { backgroundColor: colors.backgroundCard },
            ]}
          >
            <Icon
              iconFamily="MaterialCommunityIcons"
              name="close"
              size={rs.scale(20)}
              color={colors.textPrimary}
            />
          </Pressable>
        </View>
        <View style={s.center}>
          <Text
            style={[
              s.notFoundText,
              { color: colors.textTertiary, fontFamily: fonts.Regular },
            ]}
          >
            Meal details not available
          </Text>
          <Button
            label="Go back"
            onPress={goBack}
            variant="ghost"
            fullWidth={false}
          />
        </View>
      </ScreenWrapper>
    );
  }

  return (
    <ScreenWrapper>
      <LinearGradient
        colors={[meta.color + '30', colors.background]}
        style={[s.hero, { paddingTop: insets.top + rs.verticalScale(16) }]}
      >
        <Pressable
          onPress={goBack}
          style={[
            s.closeBtnInner,
            universalStyles.flexEnd,
            {
              backgroundColor: colors.backgroundCard,
              marginBottom: rs.verticalScale(16),
            },
          ]}
        >
          <Icon
            iconFamily="MaterialCommunityIcons"
            name="close"
            size={rs.scale(20)}
            color={colors.textPrimary}
          />
        </Pressable>

        <View style={s.heroContent}>
          <View
            style={[
              s.mealIconBig,
              {
                backgroundColor: meta.color + '20',
                borderColor: meta.color + '40',
              },
            ]}
          >
            <Text style={{ fontSize: rs.scale(44) }}>{meta.emoji}</Text>
          </View>

          <View style={s.heroText}>
            <View style={s.heroTitleRow}>
              <Badge
                label={meta.label}
                style={[
                  universalStyles.borderWidthOne,
                  {
                    backgroundColor: meta.color + '20',
                    borderColor: meta.color + '40',
                  },
                ]}
              />
              <Badge label={meta.time} variant="default" small />
            </View>
            <Text
              style={[
                s.mealName,
                { color: colors.textPrimary, fontFamily: fonts.Bold },
              ]}
            >
              {meal.name}
            </Text>
            <Text
              style={[
                s.mealDesc,
                { color: colors.textTertiary, fontFamily: fonts.Regular },
              ]}
            >
              {meta.desc}
            </Text>
          </View>
        </View>
      </LinearGradient>
      <ScreenWrapper
        contentStyle={[
          s.content,
          { paddingBottom: insets.bottom + rs.verticalScale(32) },
        ]}
        scroll
      >
        <View
          style={[
            s.calorieStrip,
            {
              backgroundColor: colors.backgroundCard,
              borderColor: colors.border,
            },
          ]}
        >
          {[
            {
              label: 'Calories',
              value: meal.calories,
              unit: 'kcal',
              color: meta.color,
            },
            {
              label: 'Protein',
              value: meal.protein,
              unit: 'g',
              color: '#10B981',
            },
            { label: 'Carbs', value: meal.carbs, unit: 'g', color: '#F59E0B' },
            { label: 'Fat', value: meal.fat, unit: 'g', color: '#EF4444' },
          ].map(n => (
            <View key={n.label} style={s.nutrientItem}>
              <Text
                style={[
                  s.nutrientVal,
                  { color: n.color, fontFamily: fonts.Bold },
                ]}
              >
                {n.value}
                <Text style={[s.nutrientUnit, { color: colors.textTertiary }]}>
                  {n.unit}
                </Text>
              </Text>
              <Text
                style={[
                  s.nutrientLabel,
                  { color: colors.textTertiary, fontFamily: fonts.Regular },
                ]}
              >
                {n.label}
              </Text>
            </View>
          ))}
        </View>

        {plan && (
          <View
            style={[
              s.card,
              {
                backgroundColor: colors.backgroundCard,
                borderColor: colors.border,
              },
            ]}
          >
            <Text
              style={[
                s.cardTitle,
                { color: colors.textSecondary, fontFamily: fonts.SemiBold },
              ]}
            >
              % of daily target
            </Text>
            <MacroBar
              label="Protein"
              current={meal.protein}
              target={plan.targetProtein}
              color="#10B981"
            />
            <MacroBar
              label="Carbs"
              current={meal.carbs}
              target={plan.targetCarbs}
              color="#F59E0B"
            />
            <MacroBar
              label="Fat"
              current={meal.fat}
              target={plan.targetFat}
              color="#EF4444"
            />
          </View>
        )}

        <View
          style={[
            s.infoRow,
            {
              backgroundColor: colors.backgroundCard,
              borderColor: colors.border,
            },
          ]}
        >
          <Icon
            iconFamily="MaterialCommunityIcons"
            name="clock-outline"
            size={rs.scale(18)}
            color={colors.primary}
          />
          <Text
            style={[
              s.infoLabel,
              { color: colors.textSecondary, fontFamily: fonts.Medium },
            ]}
          >
            Prep time
          </Text>
          <Text
            style={[
              s.infoVal,
              { color: colors.textPrimary, fontFamily: fonts.SemiBold },
            ]}
          >
            {meal.prepTime > 0
              ? `${meal.prepTime} minutes`
              : 'Quick — under 5 min'}
          </Text>
        </View>

        {meal.ingredients && meal.ingredients.length > 0 && (
          <View
            style={[
              s.card,
              {
                backgroundColor: colors.backgroundCard,
                borderColor: colors.border,
              },
            ]}
          >
            <Text
              style={[
                s.cardTitle,
                { color: colors.textSecondary, fontFamily: fonts.SemiBold },
              ]}
            >
              🛒 Ingredients
            </Text>
            <View style={s.ingredientGrid}>
              {meal.ingredients.map((ing, i) => (
                <View
                  key={i}
                  style={[
                    s.ingredientChip,
                    {
                      backgroundColor: colors.backgroundSurface,
                      borderColor: colors.border,
                    },
                  ]}
                >
                  <Text
                    style={[
                      s.ingredientText,
                      {
                        color: colors.textSecondary,
                        fontFamily: fonts.Regular,
                      },
                    ]}
                  >
                    {ing}
                  </Text>
                </View>
              ))}
            </View>
          </View>
        )}

        <View
          style={[
            s.tipsCard,
            {
              backgroundColor: colors.primary + '10',
              borderColor: colors.primary + '25',
            },
          ]}
        >
          <Icon
            iconFamily="MaterialCommunityIcons"
            name="lightbulb-outline"
            size={rs.scale(18)}
            color={colors.primary}
            style={{ marginBottom: rs.verticalScale(6) }}
          />
          <Text
            style={[
              s.tipsTitle,
              { color: colors.primary, fontFamily: fonts.SemiBold },
            ]}
          >
            💡 Tip
          </Text>
          <Text
            style={[
              s.tipsText,
              { color: colors.textSecondary, fontFamily: fonts.Regular },
            ]}
          >
            Eat this meal fresh for best nutrition. Pairing with a glass of
            water 30 minutes before helps with digestion and satiety.
          </Text>
        </View>

        <Button
          label="Share this meal"
          onPress={handleShare}
          variant="ghost"
          iconLeft="share-variant-outline"
          size="md"
        />
      </ScreenWrapper>
    </ScreenWrapper>
  );
};

export default MealDetailScreen;

const s = StyleSheet.create({
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: rs.verticalScale(16),
  },
  notFoundText: { fontSize: rs.font(14) },
  closeBtn: { position: 'absolute', right: rs.scale(16), zIndex: 10 },
  closeBtnInner: {
    width: rs.scale(36),
    height: rs.scale(36),
    borderRadius: rs.scale(18),
    alignItems: 'center',
    justifyContent: 'center',
  },
  hero: {
    paddingHorizontal: rs.scale(16),
    paddingBottom: rs.verticalScale(16),
  },
  heroContent: {
    flexDirection: 'row',
    gap: rs.scale(14),
    alignItems: 'flex-start',
  },
  mealIconBig: {
    width: rs.scale(72),
    height: rs.scale(72),
    borderRadius: rs.scale(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    flexShrink: 0,
  },
  heroText: { flex: 1, gap: rs.verticalScale(6) },
  heroTitleRow: { flexDirection: 'row', gap: rs.scale(6), flexWrap: 'wrap' },
  mealName: { fontSize: rs.font(20), lineHeight: rs.font(27) },
  mealDesc: { fontSize: rs.font(12), lineHeight: rs.font(18) },
  content: { paddingHorizontal: rs.scale(16), gap: rs.verticalScale(12) },
  calorieStrip: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRadius: rs.scale(14),
    borderWidth: 0.5,
    paddingVertical: rs.verticalScale(14),
  },
  nutrientItem: { alignItems: 'center', gap: rs.verticalScale(2) },
  nutrientVal: { fontSize: rs.font(18) },
  nutrientUnit: { fontSize: rs.font(11) },
  nutrientLabel: { fontSize: rs.font(11) },
  card: {
    borderRadius: rs.scale(14),
    borderWidth: 0.5,
    padding: rs.scale(14),
    gap: rs.verticalScale(8),
  },
  cardTitle: {
    fontSize: rs.font(12),
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: rs.verticalScale(4),
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs.scale(10),
    borderRadius: rs.scale(14),
    borderWidth: 0.5,
    padding: rs.scale(14),
  },
  infoLabel: { flex: 1, fontSize: rs.font(14) },
  infoVal: { fontSize: rs.font(14) },
  ingredientGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: rs.scale(8) },
  ingredientChip: {
    borderRadius: rs.scale(8),
    borderWidth: 0.5,
    paddingHorizontal: rs.scale(10),
    paddingVertical: rs.verticalScale(5),
  },
  ingredientText: { fontSize: rs.font(13) },
  tipsCard: {
    borderRadius: rs.scale(14),
    borderWidth: 1,
    padding: rs.scale(14),
  },
  tipsTitle: { fontSize: rs.font(14), marginBottom: rs.verticalScale(4) },
  tipsText: { fontSize: rs.font(13), lineHeight: rs.font(20) },
});
